version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL
    env_file:
      - .env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend